export let all_questions = [
    {
        id: 0,
        points: 2,
        flag: false,
        type: "multiple-choice",
        algebra_term: "Monomial",
        unit: "Unit 1",
        category: "Category 1",
        difficulty: "Easy",
        teks: ["TEKS-S1", "TEKS-S2", "TEKS-S14"],
        title: "Question 1",
        question:
            "This is a math world question 1. Lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsu?",
        choices: ["Option 1", "Option 2", "Option 3"],
        answer: "",
    },
    {
        id: 1,
        points: 2,
        flag: false,
        type: "open-response",
        algebra_term: "Polynomial",
        unit: "Unit 2",
        category: "Category 3",
        difficulty: "Difficult",
        teks: ["TEKS-S1", "TEKS-S8", "TEKS-S13"],
        title: "Question 2",
        question:
            "This is a math world question 2. Lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsu?",
        choices: ["Option 1", "Option 2", "Option 3"],
        answer: "",
    },
    {
        id: 2,
        points: 3,
        flag: false,
        type: "checkbox",
        algebra_term: "Binomial",
        unit: "Unit 3",
        category: "Category 2",
        difficulty: "Average",
        teks: ["TEKS-S3", "TEKS-S19", "TEKS-S11"],
        title: "Question 3",
        question:
            "This is a math world question 3. Lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsu?",
        choices: ["Option 1", "Option 2", "Option 3"],
        answer: [],
    },
    {
        id: 3,
        points: 2,
        flag: false,
        type: "range-type",
        algebra_term: "Binomial",
        unit: "Unit 3",
        category: "Category 2",
        difficulty: "Average",
        teks: ["TEKS-S4", "TEKS-S3", "TEKS-S5"],
        title: "Question 4",
        question:
            "This is a math world question 4. Lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsu?",
        choices: ["Option 1", "Option 2", "Option 3"],
        answer: [null, null],
    },
    {
        id: 4,
        points: 3,
        flag: false,
        type: "drag-and-drop",
        algebra_term: "Binomial",
        unit: "Unit 3",
        category: "Category 2",
        difficulty: "Average",
        teks: ["TEKS-S5", "TEKS-S12", "TEKS-S16"],
        title: "Question 5",
        question:
            "This is a math world question 5. Lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsu?",
        choices: ["Option 1", "Option 2", "Option 3"],
        answer: [],
    },
    {
        id: 5,
        points: 3,
        flag: false,
        type: "graph-type",
        algebra_term: "Binomial",
        unit: "Unit 3",
        category: "Category 2",
        difficulty: "Average",
        teks: ["TEKS-S5", "TEKS-S12", "TEKS-S16"],
        title: "Question 5",
        question:
            "This is a math world question 5. Lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsu?",
        choices: ["Option 1", "Option 2", "Option 3"],
        answer: [],
    },
];
